#!/bin/bash
# What file contains the RSA keys of systems that are authorized to connect via SSH?

cat ~/.ssh/authorized_keys
# The directory might be empty, but a key can be created with the command ssh-keygen.