#!/bin/bash
# Write a script which displays only the login, UID and Path of each entry of the /etc/passwd file.

cat /etc/passwd | awk -F ":" 'FNR>10 {print $1 " " $3 " " $6}' | column -t
# column -t, a new thing, will arrange it nicely